

# Site settings
title: B. Maser
description: <br>M.Sc Student</br><br>Department of Computer Science</br>University of Salzburg
email: babak.maser@stud.sbg.ac.at
markdown: kramdown
theme: jekyll-theme-minimal

