

# Site settings
title: B. Maser
description: M.Sc. Computer Science Graduate,University of Pune &<br>M.Sc Student at <br>the University of Salzburg
email: babak.maser@stud.sbg.ac.at
markdown: kramdown
theme: jekyll-theme-minimal

# logo: [Location of the logo]
show_downloads: false 
google_analytics: [UA-176866426-1]
